source "https://supermarket.getchef.com"

cookbook 'apache2'
cookbook 'openssl'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql'
cookbook 'php'
cookbook 'memcached'
cookbook 'lamp', path: './chef/cookbooks/lamp'

