# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

vconfig = YAML::load_file("config/config.yml")
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use the omnibus installer for the latest Chef installation
	config.omnibus.chef_version = :latest
  
  # Enable Berkshelf support
	config.berkshelf.enabled = true
  
  # Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = vconfig['vagrant']['box']
    config.vm.box_url = vconfig['vagrant']['box_url']

  # Set share folder
	config.vm.synced_folder "../site" , "/var/www/" + vconfig['site']['name'] + "/", :mount_options => ["dmode=777", "fmode=666"]
	
  # Use hostonly network with a static IP 
  # Hostmanager can sort host file entries automatically

	config.hostmanager.enabled = true
	config.hostmanager.manage_host = true
	
	config.vm.define vconfig['site']['name'] do |node|
		node.vm.hostname = vconfig['site']['name'] + ".localhost"
		node.vm.network :private_network, ip: vconfig['vagrant']['network_ip']
		node.hostmanager.aliases = [ "www." + vconfig['site']['name'] + ".localhost" ]
	end
	
	config.vm.provision :hostmanager

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
	config.vm.provider :virtualbox do |vb|
	# Use VBoxManage to customize the VM. For example to change memory:
		vb.customize ["modifyvm", :id, "--memory", "1024"]
	end

	config.vm.provision :chef_solo do |chef|
		chef.add_recipe "lamp::packages"
		chef.add_recipe "lamp::webserver"
		chef.add_recipe "lamp::vhost"
		chef.add_recipe "memcached"
		chef.add_recipe "lamp::db"
		chef.json = {
		  :app => {
			# Project name
			:name           => vconfig['site']['name'],

			# Name of db to create
			:db_name        => vconfig['site']['database_name'],

			# vhost entries
			:server_name    => vconfig['site']['name'] + ".localhost",
			:server_aliases =>  [ "www." + vconfig['site']['name'] + ".localhost" ],

			# Docroot for vhost
			:docroot        => "/var/www/" + vconfig['site']['name'] + "/public",

			# General linux packages
			:packages   => %w{ vim git screen curl },
			
			# PHP extensions
			:php_packages   => %w{ php5-mysqlnd php5-curl php5-mcrypt php5-memcached php5-gd }
		  },
		  :mysql => {
			:server_root_password   => vconfig['site']['database_password'],
			:server_repl_password   => vconfig['site']['database_password'],
			:server_debian_password => vconfig['site']['database_password'],
			:bind_address           => vconfig['vagrant']['network_ip'],
			:allow_remote_root      => true
		  }
		  
		}
	end
  
end
