vagrant:
  box: "hashicorp/precise64"
  box_url: "http://files.vagrantup.com/precise64.box"
  network_ip: "192.168.20.21"

site:
  name: "virtualbox"
  database_name: "nates_database"
  database_password: "840av840av"